version: 0.2

phases:
  pre_build:
    commands:
      - aws sts get-caller-identity
  build:
    commands:
      - docker version
      - docker build .
  post_build:
    commands:
      - helm version
